// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uhbayzsjqtusvqzfycsv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVoYmF5enNqcXR1c3ZxemZ5Y3N2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg1MjcyMjMsImV4cCI6MjA1NDEwMzIyM30.VfgQz-9dG6_Vjlo_VrHa1m4drSsl6ij5fKA_Hw5fqWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);